name: Publish Docker image
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
  api_image:
    needs: [build]
    name: Push Event API image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: janakerman
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Generate short Git sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: cmd/api/Dockerfile
          push: true
          tags: janakerman/flux-event-api:${{ steps.vars.outputs.sha_short }}
  controller_image:
    needs: [build]
    name: Push Event Controller image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: janakerman
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Generate short Git sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: cmd/controller/Dockerfile
          push: true
          tags: janakerman/flux-event-controller:${{ steps.vars.outputs.sha_short }}
