name: Publish Docker image
on: [tags]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.0'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
  api_image:
    name: Push Event API image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: janakerman
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: cmd/api/Dockerfile
          push: true
          tags: janakerman/flux-event-api:${{ steps.get_version.outputs.VERSION }}
  controller_image:
    name: Push Event Controller image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: janakerman
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: cmd/controller/Dockerfile
          push: true
          tags: janakerman/flux-event-controller:${{ steps.get_version.outputs.VERSION }}
